apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
  namespace: default
spec:
  securityContext:
    runAsUser: 99999  # Invalid user ID
  containers:
    - name: broken-container
      image: nginx:latest
      securityContext:
        privileged: true  # Overly permissive setting
      volumeMounts:
        - mountPath: "/data"
          name: missing-volume  # This volume does not exist
  volumes:
    - name: existing-volume  # Incorrect volume reference
      emptyDir: {}
